# Generated by Django 3.0.3 on 2020-05-28 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('jobTitle', models.CharField(max_length=255)),
                ('hours', models.IntegerField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
